// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: company.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_company_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_company_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_company_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_company_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_company_2eproto;
class Record;
struct RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Record* Arena::CreateMaybeMessage<::Record>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Record final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Record) */ {
 public:
  inline Record() : Record(nullptr) {}
  ~Record() override;
  explicit PROTOBUF_CONSTEXPR Record(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Record(const Record& from);
  Record(Record&& from) noexcept
    : Record() {
    *this = ::std::move(from);
  }

  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  inline Record& operator=(Record&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Record& default_instance() {
    return *internal_default_instance();
  }
  static inline const Record* internal_default_instance() {
    return reinterpret_cast<const Record*>(
               &_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Record& a, Record& b) {
    a.Swap(&b);
  }
  inline void Swap(Record* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Record* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Record* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Record>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Record& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Record& from) {
    Record::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Record* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Record";
  }
  protected:
  explicit Record(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAdressFieldNumber = 2,
    kAgeFieldNumber = 3,
    kYearFieldNumber = 1,
    kVedFieldNumber = 4,
  };
  // required string adress = 2;
  bool has_adress() const;
  private:
  bool _internal_has_adress() const;
  public:
  void clear_adress();
  const std::string& adress() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_adress(ArgT0&& arg0, ArgT... args);
  std::string* mutable_adress();
  PROTOBUF_NODISCARD std::string* release_adress();
  void set_allocated_adress(std::string* adress);
  private:
  const std::string& _internal_adress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_adress(const std::string& value);
  std::string* _internal_mutable_adress();
  public:

  // optional string age = 3;
  bool has_age() const;
  private:
  bool _internal_has_age() const;
  public:
  void clear_age();
  const std::string& age() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_age(ArgT0&& arg0, ArgT... args);
  std::string* mutable_age();
  PROTOBUF_NODISCARD std::string* release_age();
  void set_allocated_age(std::string* age);
  private:
  const std::string& _internal_age() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_age(const std::string& value);
  std::string* _internal_mutable_age();
  public:

  // required int32 year = 1;
  bool has_year() const;
  private:
  bool _internal_has_year() const;
  public:
  void clear_year();
  int32_t year() const;
  void set_year(int32_t value);
  private:
  int32_t _internal_year() const;
  void _internal_set_year(int32_t value);
  public:

  // optional bool ved = 4;
  bool has_ved() const;
  private:
  bool _internal_has_ved() const;
  public:
  void clear_ved();
  bool ved() const;
  void set_ved(bool value);
  private:
  bool _internal_ved() const;
  void _internal_set_ved(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Record)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr adress_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr age_;
    int32_t year_;
    bool ved_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_company_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Record

// required int32 year = 1;
inline bool Record::_internal_has_year() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Record::has_year() const {
  return _internal_has_year();
}
inline void Record::clear_year() {
  _impl_.year_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline int32_t Record::_internal_year() const {
  return _impl_.year_;
}
inline int32_t Record::year() const {
  // @@protoc_insertion_point(field_get:Record.year)
  return _internal_year();
}
inline void Record::_internal_set_year(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.year_ = value;
}
inline void Record::set_year(int32_t value) {
  _internal_set_year(value);
  // @@protoc_insertion_point(field_set:Record.year)
}

// required string adress = 2;
inline bool Record::_internal_has_adress() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Record::has_adress() const {
  return _internal_has_adress();
}
inline void Record::clear_adress() {
  _impl_.adress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Record::adress() const {
  // @@protoc_insertion_point(field_get:Record.adress)
  return _internal_adress();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_adress(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.adress_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.adress)
}
inline std::string* Record::mutable_adress() {
  std::string* _s = _internal_mutable_adress();
  // @@protoc_insertion_point(field_mutable:Record.adress)
  return _s;
}
inline const std::string& Record::_internal_adress() const {
  return _impl_.adress_.Get();
}
inline void Record::_internal_set_adress(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.adress_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_adress() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.adress_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_adress() {
  // @@protoc_insertion_point(field_release:Record.adress)
  if (!_internal_has_adress()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.adress_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.adress_.IsDefault()) {
    _impl_.adress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_adress(std::string* adress) {
  if (adress != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.adress_.SetAllocated(adress, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.adress_.IsDefault()) {
    _impl_.adress_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.adress)
}

// optional string age = 3;
inline bool Record::_internal_has_age() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Record::has_age() const {
  return _internal_has_age();
}
inline void Record::clear_age() {
  _impl_.age_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Record::age() const {
  // @@protoc_insertion_point(field_get:Record.age)
  return _internal_age();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Record::set_age(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.age_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Record.age)
}
inline std::string* Record::mutable_age() {
  std::string* _s = _internal_mutable_age();
  // @@protoc_insertion_point(field_mutable:Record.age)
  return _s;
}
inline const std::string& Record::_internal_age() const {
  return _impl_.age_.Get();
}
inline void Record::_internal_set_age(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.age_.Set(value, GetArenaForAllocation());
}
inline std::string* Record::_internal_mutable_age() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.age_.Mutable(GetArenaForAllocation());
}
inline std::string* Record::release_age() {
  // @@protoc_insertion_point(field_release:Record.age)
  if (!_internal_has_age()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.age_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.age_.IsDefault()) {
    _impl_.age_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Record::set_allocated_age(std::string* age) {
  if (age != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.age_.SetAllocated(age, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.age_.IsDefault()) {
    _impl_.age_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Record.age)
}

// optional bool ved = 4;
inline bool Record::_internal_has_ved() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Record::has_ved() const {
  return _internal_has_ved();
}
inline void Record::clear_ved() {
  _impl_.ved_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool Record::_internal_ved() const {
  return _impl_.ved_;
}
inline bool Record::ved() const {
  // @@protoc_insertion_point(field_get:Record.ved)
  return _internal_ved();
}
inline void Record::_internal_set_ved(bool value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.ved_ = value;
}
inline void Record::set_ved(bool value) {
  _internal_set_ved(value);
  // @@protoc_insertion_point(field_set:Record.ved)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_company_2eproto
